CREATE TABLE SIKAYET_ILETISIM (
                                  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                  AD_SOYAD VARCHAR2(100) NOT NULL,
                                  E_MAIL VARCHAR2(100),
                                  TELEFON VARCHAR2(20),
                                  KONU VARCHAR2(200) NOT NULL,
                                  MESAJ CLOB NOT NULL,
                                  KATEGORI VARCHAR2(50),
                                  ONCELIK VARCHAR2(20) DEFAULT 'NORMAL',
                                  DURUM VARCHAR2(30) DEFAULT 'BEKLEMEDE',
                                  OLUSTURMA_TARIHI TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  GUNCELLEME_TARIHI TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  YANIT CLOB,
                                  YANITLAYAN_PERSONEL VARCHAR2(100),
                                  YANIT_TARIHI TIMESTAMP,
                                  ADRES VARCHAR2(500),
                                  MAHALLE VARCHAR2(100),
                                  ILCE VARCHAR2(50)
);

CREATE OR REPLACE TRIGGER TRG_SIKAYET_ILETISIM_U
BEFORE UPDATE ON SIKAYET_ILETISIM
                  FOR EACH ROW
BEGIN
  :NEW.GUNCELLEME_TARIHI := SYSTIMESTAMP;
END;
/

CREATE INDEX IDX_SIKAYET_DURUM ON SIKAYET_ILETISIM(DURUM);
CREATE INDEX IDX_SIKAYET_KATEGORI ON SIKAYET_ILETISIM(KATEGORI);
CREATE INDEX IDX_SIKAYET_ONCELIK ON SIKAYET_ILETISIM(ONCELIK);
CREATE INDEX IDX_SIKAYET_OLUSTURMA_TARIHI ON SIKAYET_ILETISIM(OLUSTURMA_TARIHI);
CREATE INDEX IDX_SIKAYET_MAHALLE ON SIKAYET_ILETISIM(MAHALLE);
CREATE INDEX IDX_SIKAYET_ILCE ON SIKAYET_ILETISIM(ILCE);
CREATE INDEX IDX_SIKAYET_EMAIL ON SIKAYET_ILETISIM(E_MAIL);
CREATE INDEX IDX_SIKAYET_TELEFON ON SIKAYET_ILETISIM(TELEFON);

-- Örnek veri
INSERT INTO SIKAYET_ILETISIM (AD_SOYAD, E_MAIL, TELEFON, KONU, MESAJ, KATEGORI, ONCELIK, ADRES, MAHALLE, ILCE)
VALUES ('Ahmet Yılmaz', 'ahmet@email.com', '0532 123 45 67', 'Yol Çalışması', 'Merkez mahallede yol çalışması yapılıyor, trafik çok sıkışık.', 'ALTYAPI', 'YÜKSEK', 'Merkez Mah. Atatürk Cad. No:123', 'Merkez', 'Gebze');

COMMIT;
drop table SIKAYET_ILETISIM